### ISSUE TITLE
多表关联

### ISSUE THREAD

**Issue by fangcaiquan** [Wanchaochao/laravel-repository#1]
这个多表关联是不是基于orm的？表的关联不能用leftjoin吗？

**Comment by myloveGy** [comment]
是基于 laravel 的 orm ! laravel 中的 orm 中的关联就不支持 left join 这种关联！关联关系只有一对一，一对多等， lefe join 这个是连表查询； 如果要 left join 这种自己写就好了！ 或者使用 scope 去实现 ，可以参考[使用scope查询](https://wanchaochao.github.io/laravel-repository/?page=repository.zh-cn#1.5-%E6%9F%A5%E8%AF%A2%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8)
