### ISSUE TITLE
About Code Comments

### ISSUE THREAD

**Issue by bsormagec** [Wanchaochao/laravel-repository#2]
Hello friend can you change code comments to english ?  It occurring errors when we are using it latin encoding editors. Can you fix them ? On Cli Commands and code comments. Thanks @Wanchaochao and @myloveGy

**Comment by myloveGy** [comment]
Hello! We have changed the comment to English and you need to update the version to v1.0.15.

**Comment by bsormagec** [comment]
thanks friend
