### ISSUE TITLE
Is there any plan for caching ?

### ISSUE THREAD

**Issue by bsormagec** [Wanchaochao/laravel-repository#3]
Hello @Wanchaochao and @myloveGy   do you have any plan for cache repositories ?

**Comment by myloveGy** [comment]
Hello! Cache processing involves too much business logic. If it is handled uniformly in the base library, there is no good way to think about it. At present, the library only adds, modifies, deletes, and provides event methods, which can be used for subsequent processing, such as cache clearing.
You can refer to: [Description](https://wanchaochao.github.io/laravel-repository/?page=repository.zh-cn#%E5%9B%9B-%E5%A2%9E%E5%88%A0%E6%94%B9%E7%9A%84%E4%BA%8B%E4%BB%B6%E6%96%B9%E6%B3%95)
