### ISSUE TITLE
QueryBuilder from request

### ISSUE THREAD

**Issue by bsormagec** [Wanchaochao/laravel-repository#4]
Hello Friend,
Is there any way to get query builder from request's. You can check it from package below.
https://bitbucket.org/zerospam/laraval-cacheable-repository/src/master/
Thanks.

**Comment by myloveGy** [comment]
Hello, now is the support request to get the query object
E.g

Request parameter：

http://localhost/users?name:like=John&email:auto_like=test&status=1&age:gt=10&limit=10&offset=20

PHP code：

```php
$users = $this->repository->findAll($request->all());
```

The SQL generated by the above example is as follows:

```SQL
SELECT
	`users`.* 
FROM
	`users` 
WHERE
	`users`.`name` LIKE 'John' 
	AND `users`.`email` like 'test'
	AND `users`.`status` = 1 
	AND `users`.`age` > 10 
	LIMIT = 10 OFFSET 20
```

The find, findAll, paginate, filterFind, filterFindAll, and filterPaginate in the repository all support the direct query of the above request parameters.

The above example may be able to meet your needs, but I personally don't recommend this.
