### ISSUE TITLE
模型中有created_at字段无法自动处理了。

### ISSUE THREAD

**Issue by lovetd** [Wanchaochao/laravel-repository#5]
我在插入数据的时候， 对应模型里的created_at 字段是没有同时填充的， 而我用原始方式创建的model是有保存的。

**Comment by myloveGy** [comment]
能否贴出你的代码，model 类 、repository 类，以及你使用的 
laravel-repository 的版本

**Comment by myloveGy** [comment]
我在本地测试，没有发现你的问题，需要你自己检测你的 model 是否有设置不更新created_at 字段、repository 调用的也是 model 的 create 方法，理论上不会出现 model 可以 而 repository 不能的问题

**Comment by lovetd** [comment]
抱歉， 之前可能是晚上写的代码， 写晕了，导致没有生效。 第二天仔细查看源码后调用create方法， 问题解决了。 让你费心了。
