### ISSUE TITLE
关于数据格式化的问题

### ISSUE THREAD

**Issue by dreamcog** [Wanchaochao/laravel-repository#6]
在使用过程中，发现经常需要对数据进行格式化。比如添加关联的其他表的数据。

举例，比如一个User关联了一个Profile，那么在find方法获得的这个User因为不是对象，因为默认返回的是toArray以后的数据，不能直接用user->profile的方法来获得对应的profile的数据。

这部分的建议是如何解决？

**Comment by myloveGy** [comment]
使用 first 方法，用法和 find 一样，只是一个返回的是对象一个返回的数组

**Comment by dreamcog** [comment]
我在使用过程中的确遇到了挺多类似的问题。

比如我现在在写afterCreate方法，希望能记录管理员的log，因为希望记录的是原生的数据库内容。我的模型设置了一些getAttribute的方法。

但是因为afterCreate回调里面，传入的数据是array。就没有办法用getAttribute来获得原生的数据库的数据。

我一直觉得是否所有的返回都采用Model的对象会更好一些？当时我们设计的时候这些部分用Array的返回的考虑是什么呢？

**Comment by myloveGy** [comment]
查询返回对象和数组的方法都是存在的，这个看个人使用习惯。

返回数组：find, findAll, findAllBy
返回对象：first
返回集合对象: get, pluck

我更倾向于用数组的原因：
1 、PHP 本身就提供了很多操作数组的方法( laravel 集合也有很多辅助方法)
2、laravel 提供的辅助函数 Arr::get 方法，只能操作数组，在项目中使用这个辅助函数比较频繁（laravel 也有 data_get 方法）

这些也是我的习惯了

至于所有返回都需要返回model对象，觉得不太妥当， 对于修改和删除怎么处理，主要使用的是多删除和多修改；返回 model，对于后续操作比较方便，但 model 和 repository 的界限就模糊了

**Comment by dreamcog** [comment]
另外还有一个问题，你倾向于把数据的格式化放在哪一层呢？

比如说我有一个load方法，每次去load一个user.
但是在user获得数据以后，还要根据user_id去profile表查一个profile放到user数组里面。

这时候，这个格式化的工作我们在哪儿做比较妥当？
谢谢！

**Comment by myloveGy** [comment]
你 load 数据的时候，可以通过model 的关联直接查询出 profile （前提示你的 user model 定义了和profile 的关联关系):

```php
$info = $this->userRepository->find(['user_id' => 1], ['*', 'prefile' => ['id', 'profile', ....]]);

// 查询返回的数组结构
[
     'user_id' => 1,
    // ... user 表字段信息
    'profile' => [
       // ... profile 字段信息
    ]
]
```
